[임정찬]Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/30-westagram-backend-1-team pull request #10
Opened 2022-02-21 08:06 UTC by L-jungchan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-21 08:26 UTC, 97woo commented on students/jungchan/users/views.py
> +            if User.objects.filter(email=email, password=password).exists():
필터로 성공여부 확인 보다 예외사항을 다 정리해준 다음 예외사항 없이  함수가 실행될때 마지막에 return 후에  성공표시를 주는게 더 낳지 않을까요??

2022-02-21 08:33 UTC, L-jungchan commented on students/jungchan/users/views.py
> +            if User.objects.filter(email=email, password=password).exists():
지금까지 리턴을 전부 try문 안에 넣어놨기 때문에 로그인 뷰도 마찬가지로 try안으로 넣었습니다!

2022-02-22 01:35 UTC, Kang-kyunghun requested changes

2022-02-22 01:35 UTC, Kang-kyunghun commented on students/jungchan/users/views.py
> +            password = data['password']
=을 기준으로 정렬해 주세요.
```suggestion
            data     = json.loads(request.body)
            email    = data['email']
            password = data['password']
```

2022-02-22 01:35 UTC, Kang-kyunghun commented on students/jungchan/users/views.py
> +                return JsonResponse({'message':'SUCCESS'}, status=200)
- 프론트로부터 입력된 email과 password가 동시에 만족하는 유저가 존재하지 않을 경우만 error을 주면 될 것 같습니다.
- 따라서 위의 각 각 판단한 조건들은 불필요할 것 같아요.
- 보안상 email이 틀렸는지, 비밀번호가 틀렸는지를 안 나타내는 것이 좋습니다. 그래서 에러 메시지도 INVALIDE_USER로 수정해 주세요.

```suggestion
            if not User.objects.filter(email=email, password=password).exists():
                return JsonResponse({'message':'INVALID_USER'}, status=401)
            
            return JsonResponse({'message':'SUCCESS'}, status=200)
```

2022-02-22 02:05 UTC, Kang-kyunghun commented
LGTM~

2022-02-22 02:05 UTC, merged