[박건우]mission4 :로그인 기능 구현
wecode-bootcamp-korea/30-westagram-backend-1-team pull request #11
Opened 2022-02-21 08:15 UTC by 97woo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
-로그인 기능 구현하였습니다.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 성공시 200반환
- 아이디 비밀번호 틀려서 로그인 실패시 invaild error 반환
- key error 400반환
- urls.py 에 login 경로 추가
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-21 08:26 UTC, L-jungchan commented on students/geonwoo/users/views.py
> +        return JsonResponse({"message": "SUCCESS"}, status=200)
로그인 시도에 대해 아무런 조건도 검사하지않았는데 SUCCESS로 리턴되는것 같습니다!

2022-02-21 08:35 UTC, 97woo commented on students/geonwoo/users/views.py
> +        return JsonResponse({"message": "SUCCESS"}, status=200)
답변 감사합니다. 로그인 요청시 예외조건 있어서 함수 리턴값 success는  데이터베이스에 있는 이메일과 패스워드를 입력해야만 success가 뜹니다.!

2022-02-22 01:29 UTC, Kang-kyunghun requested changes

2022-02-22 01:29 UTC, Kang-kyunghun commented on students/geonwoo/users/views.py
> +        return JsonResponse({"message": "SUCCESS"}, status=200)
- except로 예외 처리한 경우 가장 아래로 내려주는 것이 가독성에 더 좋습니다.
- 불필요한 공백들은 제거해 주세요.
```suggestion
            return JsonResponse({"message": "SUCCESS"}, status=200)
        except KeyError:
            return JsonResponse({"message": "KEY_ERROR"}, status=400)
```

2022-02-22 01:29 UTC, Kang-kyunghun commented on students/geonwoo/users/views.py
> +                return JsonResponse({"message":"INVALID_PASSWORD"},status=401)
```suggestion
```
보안을 위해서 아이디가 틀렸는지, 비밀번호가 틀렸는지 모르는 것이 좋습니다.

2022-02-22 01:29 UTC, Kang-kyunghun commented on students/geonwoo/users/views.py
> +                return JsonResponse({"message":"INVALID_USER"},status=401)
```suggestion
            if not User.objects.filter(email = data['email'], (password = data['password').exists():
                return JsonResponse({"message":"INVALID_USER"},status=401)
```
아이디와 비밀번호가 동시에 맞는 유저를 찾아야 되기 때문에 filter 조건에 2가지 조건을 모두 넣으면 좋을 것 같습니다.

2022-02-22 02:06 UTC, Kang-kyunghun requested changes

2022-02-22 02:06 UTC, Kang-kyunghun commented on students/geonwoo/users/views.py
> +
불필요한 공백은 항상 제거해 주세요.

2022-02-22 03:50 UTC, 97woo commented on students/geonwoo/users/views.py
> +
다시 확인하고 수정하였습니다!

2022-02-22 05:57 UTC, Kang-kyunghun commented
LGTM~!!

2022-02-22 05:57 UTC, merged