[박건우]Misson2 :모델링
wecode-bootcamp-korea/30-westagram-backend-1-team pull request #5
Opened 2022-02-17 08:36 UTC by 97woo

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-17 09:14 UTC, Kang-kyunghun requested changes

2022-02-17 09:14 UTC, Kang-kyunghun commented on students/geonwoo/users/models.py
> +    email       = models.CharField(max_length=30)
email field에 unique 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!
공식 문서에서 그 방법을 찾아보고 적용해주세요.

2022-02-17 09:14 UTC, Kang-kyunghun commented on students/geonwoo/users/models.py
> +    password    = models.CharField(max_length=20)
password property는 나중에 해시(암호화)된 비밀번호 길이를 고려해서 넉넉하게 100 이상으로 설정해주세요.

2022-02-17 09:14 UTC, Kang-kyunghun commented on students/geonwoo/users/models.py
> +    phoneNumber = models.CharField(max_length=20)
```suggestion
    phone_number = models.CharField(max_length=50)
```
python에서 변수명은 카멜 케이스가 아닌 스네이크 케이스를 사용합니다.

- phoneNumber -> phone_number
- max_length가 조금 작은 것 같습니다. 50으로 늘려주세요.

2022-02-17 09:14 UTC, Kang-kyunghun commented on students/geonwoo/users/models.py
> +
데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2022-02-17 09:14 UTC, Kang-kyunghun commented on students/geonwoo/users/models.py
> +class Sign_up(models.Model):
```suggestion
class User(models.Model):
```
class 이름은 어떤 데이터의 대한 정보인가를 나타내주어야 합니다.

2022-02-17 09:14 UTC, Kang-kyunghun commented on students/geonwoo/users/models.py
> +        db_table = "sign_ups"
```suggestion
        db_table = "users"
```

2022-02-17 11:49 UTC, 97woo commented on students/geonwoo/westargram/settings.py
> +    'westargram'
순간적으로 westargram이 앱인줄알고 추가하였는데 westargram이 프로젝트인걸 정확히 인지하였고 삭제하였습니다

2022-02-17 12:22 UTC, 97woo commented on students/geonwoo/westargram/settings.py
> +    'westargram'
전체 다 수정하고 코멘트를 다시올리려고 하다가 삭제하다가 멘토님 메세지를 삭제했습니다.죄송합니다.

2022-02-18 01:06 UTC, Kang-kyunghun requested changes

2022-02-18 01:06 UTC, Kang-kyunghun commented on students/geonwoo/users/models.py
> +    phone_number = models.CharField(max_length=50,unique=True)
unique=True 속성은 정말로 유일해야 되는 값에 붙여주는 속성입니다.
- name은 동명이인이 있을 수 있습니다.
- password도 다른 사람이 같은 비밀번호를 사용할 경우가 있습니다.
- phone_number같은 경우 조금 애매하긴 하지만, unique 속성을 걸어도 괜찮을 것 같습니다.

```suggestion
    name         = models.CharField(max_length=50)
    email        = models.CharField(max_length=50, unique=True)
    password     = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=50, unique=True)
```

2022-02-18 04:21 UTC, Kang-kyunghun commented
LGTM~!

2022-02-18 04:22 UTC, merged