[임정찬]Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/30-westagram-backend-1-team pull request #7
Opened 2022-02-18 09:04 UTC by L-jungchan

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-02-18 09:48 UTC, Kang-kyunghun requested changes

2022-02-18 09:48 UTC, Kang-kyunghun commented on students/jungchan/users/views.py
> +        try:
```suggestion
        try:
            data = json.loads(request.body)
```
data를 받는 부분도 Try안에 넣어주면 좋을 것 같습니다.

2022-02-18 09:48 UTC, Kang-kyunghun commented on students/jungchan/users/views.py
> +                return JsonResponse({'message':'KEY_ERROR'}, status=400)
Try/except로 keyerror에 대한 예외처리를 하신 것 같은데 위와 같이 또 추가한 이유가 있을까요?

2022-02-18 09:48 UTC, Kang-kyunghun commented on students/jungchan/users/views.py
> +                    return JsonResponse({'message':'Overlapped_email'}, status=400)
db에서 모든 유저 정보를 가져와 비교를 하게 되면 유저 데이터가 많아 질 수록 해당 api의 성능이 많이 떨어집니다. 
데이터의 유무를 비교할 때는 db 단에서 비교를 해야 되는데, 이 때 exists()라는 것을 사용합니다.
한 번 찾아보시고 적용해 보세요.

2022-02-18 09:48 UTC, Kang-kyunghun commented on students/jungchan/users/views.py
> +                return JsonResponse({'message':'Invalid_email'}, status=400)
```suggestion
            if not re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', data['email']):
                return JsonResponse({'message':'Invalid_email'}, status=400)
```
python에서 None을 비교할 때느 == 을 잘 사용하지 않습니다. None 자체가 False의 의미를 가지고 있기 때문입니다. 
따라서 None일 때 조건문을 실행하고 싶은면 앞에 not을 붙혀주시면 됩니다.

아래 다른 if들도 수정해 주세요.

2022-02-18 09:48 UTC, Kang-kyunghun commented on students/jungchan/users/views.py
> +            # 전부 형식에 맞게 입력했을 경우 회원정보 db에 create
어떤 기능을 나타내는지 주석으로 잘 설명해 주시고 있습니다.
사실 주석은 잘 남기면 코드를 이해하는데 많은 도움을 줄 수 있지만, 오히려 코드 해석에 방해가 될 수 있습니다.

주석을 남기는 것이나, 남기는 방법들은 회사마다 다 다르지만 위코드에서는 주석을 안 남기는 것을 컨벤션으로 삼고 있습니다.
westagram의 경우 공부의 의미로 그냥 넘어 가지만, 프로젝트 때는 다른 사람들과 협업하는 상황이기에 그 때는 주석을 삼가해 주세요.

2022-02-18 10:50 UTC, L-jungchan commented on students/jungchan/users/views.py
> +                return JsonResponse({'message':'KEY_ERROR'}, status=400)
이메일과 패스워드만 없을때에도 처리해야 하는것 같아서 이렇게 둘다 했습니다.

2022-02-21 05:53 UTC, Kang-kyunghun requested changes

2022-02-21 05:53 UTC, Kang-kyunghun commented on students/jungchan/users/views.py
> +            if not re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', data['email']):
```suggestion
            data = json.loads(request.body)
            
            if not re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', data['email']):
```

2022-02-21 07:35 UTC, Kang-kyunghun commented
LGTM~~!

2022-02-21 07:35 UTC, merged